class GameAssets {
  static const String _defaultLogo = 'assets/icon/pokeball_icon.png';

  static const Map<String, String> gameLogos = {
    'Legends: ZA': 'assets/games/legendsza.png',
    'Scarlet': 'assets/games/scarlet.png',
    'Violet': 'assets/games/violet.png',
    'Brilliant Diamond': 'assets/games/brilliantdiamond.png',
    'Shining Pearl': 'assets/games/shiningpearl.png',
    'Legends: Arceus': 'assets/games/legendsarceus.png',
    'Sword': 'assets/games/sword.png',
    'Shield': 'assets/games/shield.png',
    "Let's Go Pikachu": 'assets/games/letsgopikachu.png',
    "Let's Go Eevee": 'assets/games/letsgoeevee.png',
    'Ultra Sun': 'assets/games/ultrasun.png',
    'Ultra Moon': 'assets/games/ultramoon.png',
    'Sun': 'assets/games/sun.png',
    'Moon': 'assets/games/moon.png',
    'Omega Ruby': 'assets/games/omegaruby.png',
    'Alpha Sapphire': 'assets/games/alphasapphire.png',
    'X': 'assets/games/X.png',
    'Y': 'assets/games/Y.png',
    'Black 2': 'assets/games/black2.png',
    'White 2': 'assets/games/white2.png',
    'Black': 'assets/games/black.png',
    'White': 'assets/games/white.png',
    'HeartGold': 'assets/games/heartgold.png',
    'SoulSilver': 'assets/games/soulsilver.png',
    'Platinum': 'assets/games/platinum.png',
    'Diamond': 'assets/games/diamond.png',
    'Pearl': 'assets/games/pearl.png',
    'Emerald': 'assets/games/emerald.png',
    'Ruby': 'assets/games/ruby.png',
    'Sapphire': 'assets/games/sapphire.png',
    'FireRed': 'assets/games/firered.png',
    'LeafGreen': 'assets/games/leafgreen.png',
    'Crystal': 'assets/games/crystal.png',
    'Gold': 'assets/games/gold.png',
    'Silver': 'assets/games/silver.png',
  };

  static const List<String> games = [
    '',
    'Legends: ZA',
    'Scarlet',
    'Violet',
    'Legends: Arceus',
    'Brilliant Diamond',
    'Shining Pearl',
    'Sword',
    'Shield',
    "Let's Go Pikachu",
    "Let's Go Eevee",
    'Ultra Sun',
    'Ultra Moon',
    'Sun',
    'Moon',
    'Omega Ruby',
    'Alpha Sapphire',
    'X',
    'Y',
    'Black 2',
    'White 2',
    'Black',
    'White',
    'HeartGold',
    'SoulSilver',
    'Platinum',
    'Diamond',
    'Pearl',
    'Emerald',
    'FireRed',
    'LeafGreen',
    'Ruby',
    'Sapphire',
    'Crystal',
    'Gold',
    'Silver',
  ];

  static String logoFor(String? game) => gameLogos[game] ?? _defaultLogo;
}
